### ISSUE TITLE
Logs still present in @eth-optimism/plugins/ganache while running "truffle test"

### ISSUE THREAD

**Issue by bghughes** [ethereum-optimism/Truffle-ERC20-Example#6]
Lots of logs are being written to console while running `truffle test` with the plugin. See below:

```
getting normal provider
got normal provider
we wrapping now??
getting normal provider
got normal provider
we wrapping now??
getting normal provider
got normal provider
we wrapping now??
getting normal provider
got normal provider
we wrapping now??
getting normal provider
got normal provider
we wrapping now??
we creating VM now??
we creating VM now??
we creating VM now??
```

**Comment by bghughes** [comment]
This could be the wrong place to dump this issue - please let me know if I am in the wrong place and happy to reproduce elsewhere and provide more information

**Comment by fainashalts** [comment]
Can confirm, I see these as well.

**Comment by smartcontracts** [comment]
Hah, whoops. Sometimes we forget to delete some `console.log` statements ;-) Thank you for the report. This should be "fixed" now that we're no longer using the fork of `ethereumjs-vm` (at least for now).
